### ISSUE TITLE
Improve `Dialect` section of `Stats` page

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader#104]
**Is your feature request related to a problem? Please describe.**
The current `pie chart` under `stats` page doesn't have labels which make it hard to track which piece belongs to which dialect. In addition, the `pie chart` shows all the dialects at once, making it hard to understand the separation of dialects based on region. 

**Describe the solution you'd like**
- Including labels for each piece of the `pie chart`.
- Include other `pie charts` based on region (Gulf, Lev, North Africa, etc.).

Relevant #93

**Comment by sudomaze** [comment]
Some dialects have `NaN` value as their total.

**Comment by yousef337** [comment]
Going to use logarithmic scale to even-out the distribution on the dialects. This effect should not haven any side-effects on the countries graph. 
![Dialects](https://user-images.githubusercontent.com/56966315/180289657-25a5bf45-16f1-4456-b168-207a366a198a.png)

**Comment by yousef337** [comment]
tracked in #108
