### ISSUE TITLE
Datasets to be added to Masader

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader#12]
Refer to this [sheet](https://docs.google.com/spreadsheets/d/1bVhV0fB4K2iR1asTh1OZCaf24exzf3pkCb1oTgIjZUc/edit) for possible additions

**Comment by wmustafaAwad** [comment]
[TALAA dataset for Arabic Part of Speech](
https://github.com/seloufian/Arabic-PoS-Tagger/tree/master/src%2Fmodel%2Fcorpus)

**Comment by wmustafaAwad** [comment]
[ANERCorp - Arabic Named Entity Recognition Corpus](https://github.com/EmnamoR/Arabic-named-entity-recognition/blob/master/ANERCorp.rar)

**Comment by zaidalyafeai** [comment]
@wmustafaAwad both datasets are already in the catalogue, check https://arbml.github.io/masader/

**Comment by wmustafaAwad** [comment]
My bad 🤦‍♂️
Thank you, will check next time.

**Comment by AliOsm** [comment]
I found that you already added https://github.com/AliOsm/arabic-text-diacritization/tree/master/dataset to Masader. I think you could also add https://github.com/AliOsm/shakkelha/tree/master/dataset, this is an extension we published after the first one. The extension is just training data.

**Comment by zaidalyafeai** [comment]
Since you are an author, it is better that you add the dataset, will be much faster.
