### ISSUE TITLE
White spaces in search query leads to no results

### ISSUE THREAD

**Issue by MaramHasanain** [ARBML/masader#137]
**Describe the bug**
Adding white spaces to begging or end of the search query (dataset name) prevents the search engine from matching it to already existing datasets in the catalogue. 

**To Reproduce**
1. Go to : https://arbml.github.io/masader/search
2. Type name of dataset with a white space (or multiple) at the beginning or end (example: https://arbml.github.io/masader/search?name=artest+)
3. No results returned

**Expected behavior**
Search engine should handle such typo issue from the user as white spaces are most probably not part of any dataset name. Search engine should return the dataset even if the user added a space to its name in the search query. 

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser: Chrome

**Comment by zaidalyafeai** [comment]
Thanks @MaramHasanain, should be easily fixed by using `trim`. Let me you know if you want to create a PR.

**Comment by zaidalyafeai** [comment]
fixed by @obada-jaras, thanks.
