### ISSUE TITLE
Moving front-end to `jekyll`

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader#19]
For this issue, we will refactor the front-end code under this branch https://github.com/ARBML/masader/tree/dev/move_to_jekyll, so use it as a base for any of the tasks below:

## Core changes:
- [x] Update `js` scripts to expect data from the API endpoint
	- [x] `index.js`
	- [x] `card.js`
	- [x] `charts.js`
	- [x] `graphs.js`
- [ ] Ensure that the website is responsive on mobile screens

## Additions
- [ ] Add a simple filtering functionality for #17

**Comment by zaidalyafeai** [comment]
Hey, @sudomaze what is our timeline on this? How is working on it?

**Comment by sudomaze** [comment]
For `charts.js` and `explore.js`, I will be waiting for the latest updates for this issue, https://github.com/ARBML/masader/issues/29. Once the end-points were created for `/charts` and `explore`, I will update `charts.js` and `explore.js`.

I will be away for the next few days due to covid, so anyone who wants to tackle this issue after the update on the end-points.

**Comment by sudomaze** [comment]
This issue will be closed because it has been resolved in the latest merge to main (#48).
