### ISSUE TITLE
Masader Hosting 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader#23]
We are exploring the options of converting the website to be dynamic rather than a static html using GitHub Pages.

**Comment by AliOsm** [comment]
I propose to build simple Flask app for now. It will provide the required features like connecting to a DB. Also, the current website is like a data catalog, so I don't think that we need to use some fancy framework to do it :3

**Comment by zaidalyafeai** [comment]
I am happy with the progress, for now, we can close this issue.
