### ISSUE TITLE
Report Data Cards 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader#25]
We need a simple way to indicate if a certain dataset card has some problems. For instance, a button that opens an issue with the data id/name.

**Comment by zaidalyafeai** [comment]
Something like this https://github.com/arbml/masader/issues/new?labels=bug&title=New+bug+report

**Comment by sudomaze** [comment]
We will need to have some way to prevent spam either by using reCAPTCHA or auth the account with GitHub account to prevent who will spam using the reporting functionality.

**Comment by zaidalyafeai** [comment]
@sudomaze please create another issue, closing for now.
