### ISSUE TITLE
Show datasets corresponding to a certain dialect 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader#28]
The dialects graph in https://arbml.github.io/masader/charting.html only shows the number of resources. It will be helpful if we can show the list of datasets that correspond to a chosen country.

**Comment by zaidalyafeai** [comment]
Tracked in https://github.com/ARBML/masader/pull/59

**Comment by yousef337** [comment]
I am going to create a new branch for the new graph design. Going to update the track soon.

**Comment by yousef337** [comment]
Tracked in #86
