### ISSUE TITLE
An API endpoint to fetch data and preprocess them

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader#29]
Per what @AliOsm has done in https://github.com/ARBML/masader-webservice, we will need to add the following to complete the required tasks for the paper submission:

- [x] Get the entire datasets at once
- [x] Get a single dataset by id
- [x] Get `explore` page data in the right format
- [x] Get `graphs` page data in the right format

**Comment by AliOsm** [comment]
Also, we will need to add pagination to `/datasets` endpoint. Something like `/datasets?page=2&size=50` should return the datasets from 51 to 100.

**Comment by zaidalyafeai** [comment]
@AliOsm I have discussed with @sudomaze that this is actually not necessary now but could be useful in the future. So it is not high prioirty.

**Comment by AliOsm** [comment]
@zaidalyafeai I missed the discussion yesterday :3

Anyway, it is a 3 lines change, I can add it later today.

**Comment by zaidalyafeai** [comment]
@AliOsm I am trying to reduce the load on you but feel free to do that.

**Comment by AliOsm** [comment]
Also, I will add option to retrieve specific datasets features from the server, instead of returning the full list of 34 features for each dataset.

**Comment by zaidalyafeai** [comment]
Can we add a to-do list in https://github.com/ARBML/masader-webservice/issues?

**Comment by zaidalyafeai** [comment]
I think they are all already done @AliOsm @sudomaze ?

**Comment by AliOsm** [comment]
Yup, we are good to go.
