### ISSUE TITLE
How to add a new dataset

### ISSUE THREAD

**Issue by linuxscout** [ARBML/masader#4]
السلام عليكم
اقترح استعمال نماذج غوغل
google forms
لإرسال البيانات الجديدة
الامر اسهل من نسخ سطر وتحرير مستند
وشكرا

**Comment by zaidalyafeai** [comment]
وعليكم السلام
طرح هذا الإقتراح من قبل ، مازلت اعتقد ان الإرسال بالطريقة الحالية أكثر فعالية
لإنه يمكنك من رؤية النتائج السابقة والإقتباس منها

**Comment by zaidalyafeai** [comment]
We will use forms instead from now on.
