### ISSUE TITLE
Default chart 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader#44]
The default chart should be general stats like, number of datasets, number of dialects, number of tasks, etc.

**Comment by alotaimi** [comment]
I'm working on this ;)

**Comment by sudomaze** [comment]
<img src="https://media4.giphy.com/media/9Ai5dIk8xvBm0/giphy.gif"/>

**Comment by alotaimi** [comment]
@sudomaze 
<img src="https://media3.giphy.com/media/xTIdzKrWmAIy3dPiKX/giphy.gif"/>

**Comment by sudomaze** [comment]
We have re-designed the page to display all of the graphs at once and include `explore` page content at the beginning of the page, so we won't need to have a default chart for this release.

Resolved #93
