### ISSUE TITLE
Responsive on mobile screens

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader#46]
Updating tables, graphs, and other visual information to be responsive on mobile screens.

**Comment by zaidalyafeai** [comment]
I think the new ui will be responsible.

**Comment by sudomaze** [comment]
The new UI should be responsible for this. However, there are things that the new UI won't fix explicitly. Such as `/explore` page on the mobile view they are small (@AliOsm pointed this out)

![](https://media.discordapp.net/attachments/990261083300331590/994236376180592670/unknown.jpeg?width=957&height=441)

**Comment by zaidalyafeai** [comment]
Title and logo not responsive 
![image](https://user-images.githubusercontent.com/15667714/177903869-ecdaed7b-85c4-4b9b-8ab8-74f75c394ca7.png)

**Comment by zaidalyafeai** [comment]
Two issues 
1. The paper link column is distorted 
2. The graphs need some fixing 
![image](https://user-images.githubusercontent.com/15667714/180597971-f20d5710-2df5-4bbf-b2a1-8289517c4757.png)

**Comment by zaidalyafeai** [comment]
mostly fixed.
