### ISSUE TITLE
Reporting Functionality Protection

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader#61]
We will need to have some way to prevent spam either by using reCAPTCHA or auth the account with GitHub account to prevent who will spam using the reporting functionality.

**Comment by zaidalyafeai** [comment]
A couple of things 
1. maybe use reCAPTCHA like https://stackoverflow.com/a/70544440
2. we need a check mark to indicate that the issue has been submitted maybe also post a link to the issue so the op could follow up on that.

**Comment by yousef337** [comment]
The current mechanism gives the user the url to the issue, so they can track it

**Comment by MutlaqAldhbuiub** [comment]
..

**Comment by sudomaze** [comment]
Resolved #101
