### ISSUE TITLE
Banner and page highlighting updates 

### ISSUE THREAD

**Issue by zaidalyafeai** [ARBML/masader#66]
We want to create a page to highlight what were the main updates in this version.

**Comment by sudomaze** [comment]
#68 covers the page highlighting updates, however, it will be nice to have a notification window when a new release has been published on the website and the user isn't aware of it. This will require storing some information about the latest release that the user has seen and then displaying the release notes as a [modal](https://getbootstrap.com/docs/4.2/components/modal/#vertically-centered) or a [toast](https://getbootstrap.com/docs/4.2/components/toasts/#placement).

This might require some new endpoint that reads `CHANGELOG.md` and does some pre-processing to be fed to the front-end side. @AliOsm thoughts?

**Comment by AliOsm** [comment]
@sudomaze I don't think that processing the changelog is a good starting point, as you know, the message could be free text other than structured data points. I prefer to do simple endpoint that returns a message stored in the env vars of the service, until we decide what is the service's next step. What do you think?

**Comment by sudomaze** [comment]
The changelog has somewhat structured data.

```
## [version_num] - YYYY-MM-DD

### Added
- TEXT
- TEXT
- ...

### Changed
- TEXT
- TEXT
- ...

### Fixed
- TEXT
- TEXT
- ...

### Removed
- TEXT
- TEXT
- ...
```

A simple pre-processing function in the backend will turn the above changelog to this json:
```json
[
	{
	      "version_num": "v1.0.0",
		  "date":   "YYYY-MM-DD",
		  "added": ["TEXT", "TEXT", "..."],
		  "changed": ["TEXT", "TEXT", "..."],
		  "fixed": ["TEXT", "TEXT", "..."],
		  "removed": ["TEXT", "TEXT", "..."],
	},
]
```

**Comment by AliOsm** [comment]
I know, what I mean is that the highlight message could be free text instead of this structured data. So allowing humans to write it is better.

**Comment by sudomaze** [comment]
I was thinking of having a modal to pop-up this if the user didn't see the update before with something like this:

![](https://preview.redd.it/bn74jszjnuo61.png?auto=webp&s=70e2678915dde72e19e5d2b12e172b96b360e6da)

But if you think a simple highlight message would be enough, I can see it as a cleaner setup and we can say `read more` which will take them to the `changelog` page. I like your idea better.

**Comment by sudomaze** [comment]
cc: @grepaziz
