### ISSUE TITLE
Landing page's header

### ISSUE THREAD

**Issue by ma7dev** [ARBML/masader#72]
Rather than having a simple text like this 
![image](https://user-images.githubusercontent.com/17136125/178159357-33dc88ab-30ef-4306-a633-97e160d64922.png)
Having a more unique styling of the landing page's header like this (not black and white) 
![image](https://user-images.githubusercontent.com/17136125/178159387-19a7d325-f1a1-4b3a-bacb-310b9218bf94.png)
On mobile (not black and white) , 
![image](https://user-images.githubusercontent.com/17136125/178159401-90a0c6a1-989d-49c3-ab22-e375c4ca1d08.png)

cc: @unifoliatus

**Comment by sudomaze** [comment]
This issue will be moved to another release.
