### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader#74]
Add a search page where a user can search for datasets using keywords and filter based on tasks, dialects, license, creation date, etc.

Here is a simple layout design for it (not black and white) 
![image](https://user-images.githubusercontent.com/17136125/178159553-1ebbd052-7096-4dab-9720-1c1e1b156c47.png)

On mobile (not black and white) 
![image](https://user-images.githubusercontent.com/17136125/178159568-4b57b61f-9649-483d-a986-11b63f213e47.png)

cc: @alonemazin

**Comment by zaidalyafeai** [comment]
resolved in https://github.com/ARBML/masader/pull/123
