### ISSUE TITLE
Report element

### ISSUE THREAD

**Issue by sudomaze** [ARBML/masader#75]
Improve the UI of the report element. Currently, it looks basic.

![image](https://user-images.githubusercontent.com/17136125/178189899-ae92fc30-5eec-4de4-921b-f37a09bb64bf.png)
![image](https://user-images.githubusercontent.com/17136125/178189927-29143011-638c-4ec9-bcde-99de1869c4d9.png)

**Comment by sudomaze** [comment]
It would be nice to have a pop-up modal for reporting like this https://getbootstrap.com/docs/4.0/components/modal/#vertically-centered

**Comment by sudomaze** [comment]
Great job!

@MutlaqAldhbuiub will continue working on this as it is related to #61 (adding protection) and #79 (report dataset error). Mutlaq is planning to have two options, either submit a report using your GitHub account, which will direct you to GitHub issues and apply the report dataset error template, or submit an anonymous report which will require you to complete a reCAPTCHA.

**Comment by zaidalyafeai** [comment]
That is a good plan thank you @sudomaze and @MutlaqAldhbuiub!

**Comment by sudomaze** [comment]
Resolved #101
